---
  title: "Sumula Curricular - FAPESP"
  author: "ANDRÉ LUIZ BARBOSA NUNES DA CUNHA"
  # date: "`r Sys.Date()`"
  
  engine: knitr
  format: gfm
      #toc: true
      
---

# Formação

| Período | Duração em meses | Título ou atividade | Instituição e orientador/supervisor | Título do trabalho |
| :-----| ---: | :------------ | :-----------------------| :------------------------------|
| 1998 - 2003 | 60 | **Graduação** | Universidade Federal do Mato Grosso do Sul (UFMS)  |    |
| 2005 - 2007 | 32 | **Mestrado** | Universidade de São Paulo (USP), Escola de Engenharia de São Carlos (EESC)</br>[Prof. José Reynaldo Anselmo Setti](http://lattes.cnpq.br/1214389619505648)  | ["*Avaliação do Impacto das Medidas de Desempenho na Equivalência de Caminhões a Automóveis de Passeio*"](https://doi.org/10.11606/D.18.2007.tde-27112007-094400) |
| 2007 - 2013 | 74 | **Doutorado** | Universidade de São Paulo (USP), Escola de Engenharia de São Carlos (EESC)</br>[Prof. José Reynaldo Anselmo Setti](http://lattes.cnpq.br/1214389619505648)  | ["*Sistema Automático para a Obtenção de Parâmetros de Tráfego de Veículos a partir de Imagens de Vídeo Usando OpenCV*"](https://doi.org/10.11606/T.18.2013.tde-19112013-165611) |
| 2020 - 2020 | 12 | **Pós-Doutorado** | University of Melbourne, Australia</br>[Profa. Patricia Sauri Lavieri](https://findanexpert.unimelb.edu.au/profile/818967-patricia-sauri-lavieri) </br>[Prof. Majid Sarvi](https://findanexpert.unimelb.edu.au/profile/763544-majid-sarvi) | "*Graph-Based Approach for Spatio-Temporal Traffic Network Analysis*" |


# Histórico Profissional
<!-- Listar as principais posições profissionais que ocupou informando datas de início, término, e instituições (essas posições podem ser acadêmicas, empresariais ou administrativas, como a gestão de grandes projetos ou de instituições de ensino e pesquisa). Podem também ser listadas atividades associativas (participação em associações, federações, comissões temáticas/técnicas, conselhos de empresas/institutos/universidades), bem como atuação em empreendedorismo e startups e distinções acadêmicas e prêmios recebidos. -->


# Lista de 5 pesquisas mais relevantes e de maior impacto
<!-- podendo ser artigos científicos, livros, capítulos de livros, palestras a convite, patentes (solicitadas, concedidas e especialmente as licenciadas), softwares registrados, cultivares, empresas de base tecnológica criadas, relatórios técnicos de projetos que liderou ou em que teve papel destacado, novos produtos, novos processos ou outros tipos de resultados de pesquisa documentados que considere estarem entre as 5 mais relevantes de sua carreira. -->

<!-- Os itens deverão ser escolhidos a critério do interessado, entre aqueles que considerar mais significativos para a análise de sua produção científica e/ou tecnológica recente (principalmente nos últimos dez anos) e/ou as de maior relevância para documentar sua experiência e competência na área de conhecimento em que se insere o projeto proposto. Para cada item, inclua, quando for o caso, a quantidade de citações recebidas pelo item na literatura internacional (Web of Science, Scopus ou Google Scholar) e, em no máximo 4 linhas, outros elementos verificáveis que considerar adequados para ajudar a demonstrar o impacto do item (por exemplo: citação em patentes, licenciamento de patentes, utilização em bibliografia de cursos, impacto em políticas públicas, prêmios ao item...). Todos os autores, até um máximo de 15, deverão constar da citação. Por favor, use o padrão bibliográfico convencional em sua área e agrupe por categoria (por exemplo: artigos, patentes, capítulos...). Das listas com mais de 5 itens, a FAPESP somente utilizará no processo de análise os 5 primeiros. -->

# Lista de financiamento à pesquisa
<!-- 4.a) Auxílios vigentes, de qualquer agência ou empresa, sob a responsabilidade do Pesquisador (Pesquisador Responsável ou Pesquisador Principal), indicando: título do projeto, recursos, vigência e agência financiadora. Se for bolsista de alguma agência de fomento, indicar agência, tipo de bolsa, nível e vigência. -->

<!-- 4.b) Principais Auxílios concluídos (máximo de 5) sob a responsabilidade do Pesquisador (Pesquisador Responsável ou Pesquisador Principal) indicando: título do projeto, recursos, vigência e agências financiadoras. -->

# Indicadores quantitativos

|      |   |
| :------------------- | ----: |
| 1) livros publicados |      |
| 2) publicações em periódicos com seletiva política editorial |  |  
| 3) capítulos de livros  |    |
| 4) dissertações de Mestrado: |    |
| 4.a) orientadas e já defendidas |    |
| 4.b) em andamento   |   |
| 5) teses de Doutorado: |  |
| 5.a) orientadas e já defendidas |  |
| 5.b) em andamento |  |
| 6) supervisões de Pós-Doutorado: |  |
| 6.a) concluídas |  |
| 6.b) em andamento |  |
| 7) quantidade de citações recebidas na literatura científica internacional, segundo o Web of Science, Scopus ou Google Scholar | |
| 8) patentes solicitadas, concedidas e licenciadas |  |
| 9) produtos desenvolvidos e lançados no mercado | |
| 10) processos otimizados implementados em empresas ou organizações sociais |  |
| 11) empresas criadas ou apoiadas |  |
| 12) consultorias técnicas e científicas relevantes |  |


# Links
<!-- 6.a) Para criar o perfil ORCID consulte: https://orcid.org/. -->

<!-- 6.b) Para criar o perfil no Web of Science consulte: https://clarivate.com/products/scientific-and-academic-research/research-discovery-and-workflow-solutions/researcher-profiles/. -->

<!-- 6.c) Os perfis são criados automaticamente no Scopus quando um autor tem 2 ou mais publicações indexadas, mas o autor pode revisar e aperfeiçoar seu perfil no Scopus. Para revisar seu perfil de autor no Scopus, consulte: https://elsevier.libguides.com/Scopus/author-profile. -->

<!-- 6.d) Para criar o perfil no MyCitations do Google Scholar acesse: http://scholar.google.com. -->

- ORCID: [0000-0002-0520-0621](https://orcid.org/0000-0002-0520-0621)
- Lattes: [7996696632908127](http://lattes.cnpq.br/7996696632908127)
- Google Scholar: [HI0CQJMAAAAJ](https://scholar.google.com.br/citations?user=HI0CQJMAAAAJ&hl=pt)
- Linktree: [prof_alcunha](https://linktr.ee/prof_alcunha)

# Outras Informações
<!-- 7.a) Outras informações biográficas que julgar relevantes para a contextualização e análise de sua atividade profissional recente (últimos dez anos) e para documentar sua experiência e competência na área de conhecimento ou setor socioeconômico em que se insere o projeto proposto, ou em empreendedorismo e inovação. -->

<!-- 7.b) Descreva sua experiência internacional em pesquisa após o doutoramento evidenciando sua participação em redes internacionais de colaboração em pesquisa com resultados publicados. -->

<!-- 7.c) Indique teses orientadas que receberam prêmios acadêmicos e ex-orientandos de doutorado e ex-supervisionandos de pós-doutorado com inserção profissional destacada. -->

<!-- 7.d) Informe eventuais interrupções decorrentes de licenças médicas, de maternidade e paternidade, cuidado com outras pessoas (p. ex., enfermos, idosos, pessoas com deficiência), indicando datas de início e fim. Podem também ser informadas circunstâncias que podem ter impactado o desempenho escolar e acadêmico. -->